language: java
jdk:
  - openjdk8

branches:
  only:
    - release

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.cache"

before_install:
  - cp settings.xml $HOME/.m2/settings.xml
  - openssl enc -d -in ezframework.gpg.enc -out ezframework.gpg -aes256 -pass "pass:$SECRET_KEY_PASSWORD"
  - gpg --import ezframework.gpg
  - cd ezframework-core

script: "mvn clean deploy"

